[package]
name = "actix-web-sample"
version = "0.1.0"
authors = ["Vuraddo <vuraddo@yahoo.com>"]
edition = "2018"

[dependencies]
time = "0.1.42"
slog = "2.4.1"
slog-term = "2.4.0"
slog-json = "2.3.0"
slog-async = "2.3.0"
actix-web = "0.7.18"
